ckpt_pth: null
data_dir: /nfs4/lint/PoliData/fifteen
dataset_version: ObjectNavType
detector_usage: eval_only
eval_every: 98
eval_max_samples: 1600
exp_dir: imitation_result/pl-model=EarlyFusionCnnTransformer/object_token_small,dataset=ObjectNavType,batch_size=512,lr=0.0001,scale=100000
exp_name: 3ZhDq1dq
final_prob_sample_last_steps: 0.0
init_model: null
init_prob_sample_last_steps: 0.0
input_sensors:
- raw_navigation_camera
- nav_task_relevant_object_bbox
- nav_accurate_object_bbox
log_video_every: 50000
loss: action
lr: 0.0001
max_epochs: 80
max_samples: 100000
model: EarlyFusionCnnTransformer
model_version: object_token_small
num_datasets: 1
num_nodes: 1
output_dir: imitation_result
per_gpu_batch: 64
precision: 16-mixed
reduce_action_redundancy: false
restart_optimizer: null
resume: null
resume_local: null
run_id: null
save_every: 1000
sliding_window: 10
step: -1
use_non_strict_ckpt_loading: null
visual_debug_max_batch: 2
visual_debug_max_timestep: 4
visualize_object_tokens: false
wandb_entity_name: local
wandb_logging: false
wandb_project_name: local
